default_language: en_AU
dictionaryDefinitions:
  - name: .spelling
    path: "./.spelling"
    addWords: true
dictionaries:
  - .spelling
ignorePaths:
  - "**/.git/**"
  - ".ansible/**"
  - "**/.drawio/**"
  - "**/*.{yaml,yml,json,md,txt,log,ini,cfg,conf,env,sh,bash}"
  - ".spelling"
  - playbooks/templates/fireflyiii/**.env.j2
