---
- name: deploy-dockhand | Ensure modern version of Docker is available on host
  ansible.builtin.include_tasks:
    file: tasks/hosts-dependency-check-docker-version.yaml

####### DOCKHAND SECTION

# https://dockhand.dev/guide/hub-installation

- name: deploy-dockhand | Set Dockhand facts
  ansible.builtin.set_fact:
    dockhand_image: "{{ dockhand_image | default(' fnsys/dockhand:latest') }}"
    dockhand_service_name: "{{ dockhand_service_name | default('dockhand') }}"
    dockhand_service_port: "{{ dockhand_service_port | default(3000) }}"

- name: deploy-dockhand | Set Dockhand network facts
  ansible.builtin.set_fact:
    dockhand_network_name: "{{ dockhand_network_name | default(dockhand_service_name) }}"

- name: deploy-dockhand | Set Dockhand volume facts
  ansible.builtin.set_fact:
    dockhand_volume_name: "{{ dockhand_service_name }}"

- name: deploy-dockhand | Set Dockhand aggregated facts
  ansible.builtin.set_fact:
    dockhand_fqdn: "{{ dockhand_service_name }}.{{ ansible_hostname }}.{{ homelab.certificate_domain | default('localdomain') }}"

- name: deploy-dockhand | Set Dockhand service facts
  ansible.builtin.set_fact:
    dockhand_networks:
      # Reverse Proxy  network is used to expose applications via Traefik
      - { name: "{{ reverse_proxy_network_name | default('reverse-proxy') }}" }
    dockhand_ports:
      # Published ports to expose outside the container
      # host port:container port
      - "{{ dockhand_service_port }}:3000"
    dockhand_volumes:
      # Local paths to mount into the container
      # local path:container path
      - "{{ dockhand_volume_name }}:/app/data"

- name: deploy-dockhand | Log Dockhand configuration
  ansible.builtin.debug:
    msg:
      - "Dockhand image: {{ dockhand_image }}"
      - "Dockhand service name: {{ dockhand_service_name }}"
      - "Dockhand FQDN: {{ dockhand_fqdn }}"
      - "Dockhand networks: {{ dockhand_networks | default(omit) }}"
      - "Dockhand ports: {{ dockhand_ports | default(omit) }}"
      - "Dockhand volumes: {{ dockhand_volumes | default(omit) }}"

- name: deploy-dockhand | Create Dockhand container labels
  ansible.builtin.set_fact:
    dockhand_container_labels: "{{ dockhand_container_labels | default({}) | combine({item.key: item.value}) }}"
  with_items:
    # ---------------------------------------------------------------
    # Homepage labels
    - { "key": "homepage.group", "value": "Monitoring" }
    - { "key": "homepage.name", "value": "Dockhand" }
    - {
      "key": "homepage.description",
      "value": "Docker management you will like.",
    }
    - { "key": "homepage.icon", "value": "dockhand.png" }
    - { "key": "homepage.href", "value": "https://{{ dockhand_fqdn }}/" }
    - { "key": "homepage.siteMonitor", "value": "https://{{ dockhand_fqdn }}/" }
    # ---------------------------------------------------------------
    # Traefik labels
    - { "key": "traefik.enable", "value": "true" }
    - {
      "key": "traefik.http.routers.{{ dockhand_service_name }}.entrypoints",
      "value": "{{ traefik_entrypoint_secure_name }}",
    }
    - {
      "key": "traefik.http.routers.{{ dockhand_service_name }}.rule",
      "value": "Host(`{{ dockhand_fqdn }}`)",
    }
    # ---------------------------------------------------------------
    # What's up Docker? labels
    - { "key": "wud.tag.include", "value": '^\d+\.\d+\.\d+$$' }
    - {
      "key": "wud.link.template",
      "value": "https://github.com/Finsys/dockhand/releases/tag/v${major}.${minor}.${patch}",
    }

- name: deploy-dockhand | Create Dockhand network
  when: dockhand_networks is defined
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver | default('bridge') }}"
    internal: "{{ item.internal | default(false) }}"
    state: present
  loop: "{{ dockhand_networks }}"

- name: deploy-dockhand | Create volume for Dockhand
  when: dockhand_volume_name is defined and (dockhand_volumes | length > 0)
  community.docker.docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ dockhand_volume_name }}"

- name: deploy-dockhand | Pull Dockhand image
  community.docker.docker_image:
    name: "{{ dockhand_image }}"
    source: pull

- name: deploy-dockhand | Deploy Dockhand
  community.docker.docker_container:
    name: "{{ dockhand_service_name }}"
    image: "{{ dockhand_image }}"
    detach: true
    labels: "{{ dockhand_container_labels | default(omit) }}"
    networks_cli_compatible: true
    networks: "{{ dockhand_networks | ansible.utils.remove_keys(target=['internal']) | default(omit) }}"
    restart: true
    restart_policy: unless-stopped
    state: started
    volumes: "{{ default_host_volumes + docker_host_volume + dockhand_volumes | default(omit) }}"
  register: dockhand_container_state

- name: deploy-dockhand | Wait for Dockhand to accept connections
  ansible.builtin.wait_for:
    host: "{{ dockhand_fqdn }}"
    port: 80
    connect_timeout: 1
    delay: 10
    state: started
    timeout: 30
  register: dockhand_running
  retries: 10
  until: dockhand_running is success
