---
roles:
  - name: geerlingguy.docker
    scm: git
    src: git+https://github.com/geerlingguy/ansible-role-docker
    version: 7.9.0

  - name: geerlingguy.pip
    scm: git
    src: git+https://github.com/geerlingguy/ansible-role-pip
    version: 3.1.2
