---
- name: Deploy Termix

  hosts: ansible

  vars:

    # Termix facts
    # renovate: datasource=docker depName=ghcr.io/lukegus/termix
    termix_image: ghcr.io/lukegus/termix:release-1.8.0

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Termix
      ansible.builtin.include_tasks:
        file: tasks/deploy-termix.yaml
