---

- name: Deploy Mailrise

  hosts: ansible

  vars:

    # Mailrise facts
    # renovate: datasource=docker depName=yoryan/mailrise
    mailrise_image: yoryan/mailrise:1.7.7

    mailrise_deploy_docker_volume_backup: false

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Mailrise
      ansible.builtin.include_tasks:
        file: tasks/deploy-mailrise.yaml

    - name: Deploy a containerised instance of Docker Volume Backup
      when: mailrise_deploy_docker_volume_backup | default(false)
      ansible.builtin.include_tasks:
        file: tasks/deploy-docker-volume-backup.yaml
      vars:
        docker_volume_backup_service_name: "docker-volume-backup-{{ mailrise_service_name }}"
        docker_volume_backup_volume_to_backup:
          - "{{ mailrise_volume_name }}:/backup/{{ mailrise_service_name }}-backup:ro"
        docker_volume_backup_backup_label: "{{ mailrise_service_name }}-db"
        docker_volume_backup_backup_retention_days: 7
