---
- name: Deploy BentoPDF container

  hosts: ansible

  vars:

    # BentoPDF facts
    # renovate: datasource=docker depName=ghcr.io/alam00000/bentopdf
    bentopdf_image: ghcr.io/alam00000/bentopdf:1.10.0

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of BentoPDF
      ansible.builtin.include_tasks:
        file: tasks/deploy-bentopdf.yaml
