---
- name: Deploy AFFiNE

  hosts: ansible

  vars:
    # Affine facts
    # renovate: datasource=docker depName=ghcr.io/toeverything/affine
    affine_image: ghcr.io/toeverything/affine:0.26.2

  tasks:
    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of AFFiNE
      ansible.builtin.include_tasks:
        file: tasks/deploy-affine.yaml
