---
- name: Deploy Dockhand

  hosts: ansible

  vars:

    # Dockhand facts
    # renovate: datasource=docker depName=fnsys/dockhand
    dockhand_image: fnsys/dockhand:0d3a1a44

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Dockhand
      ansible.builtin.include_tasks:
        file: tasks/deploy-dockhand.yaml
