---
- name: Deploy Networking Toolbox

  hosts: ansible

  vars:

    # Networking Toolbox facts
    # renovate: datasource=docker depName=lissy93/networking-toolbox
    networking_toolbox_image: lissy93/networking-toolbox:1.6.0

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Networking Toolbox
      ansible.builtin.include_tasks:
        file: tasks/deploy-networking-toolbox.yaml
