---
- name: Deploy Solidtime

  hosts: ansible

  vars:

    # Solidtime facts
    # renovate: datasource=docker depName=solidtime/solidtime
    solidtime_image: solidtime/solidtime:0.10

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Solidtime
      ansible.builtin.include_tasks:
        file: tasks/deploy-solidtime.yaml

    - name: Deploy a containerised instance of Docker Volume Backup
      when: solidtime_deploy_docker_volume_backup | default(false)
      ansible.builtin.include_tasks:
        file: tasks/deploy-docker-volume-backup.yaml
      vars:
        docker_volume_backup_service_name: "docker-volume-backup-{{ solidtime_service_name }}"
        docker_volume_backup_volume_to_backup:
          - "{{ solidtime_volume_name }}:/backup/{{ solidtime_service_name }}-backup:ro"
        docker_volume_backup_backup_label: "{{ solidtime_service_name }}"
        docker_volume_backup_backup_retention_days: 7
