---
- name: Deploy Kopia

  hosts: ansible

  vars:

    # Kopia facts
    # renovate: datasource=docker depName=kopia/kopia
    kopia_image: kopia/kopia:20251203.0.174440

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Kopia
      ansible.builtin.include_tasks:
        file: tasks/deploy-kopia.yaml
