---
- name: Deploy IT Tooling Stack

  hosts: dozzle

  vars:

    # Beszel facts
    # renovate: datasource=docker depName=henrygd/beszel
    beszel_image: henrygd/beszel:0.15.4

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Beszel
      ansible.builtin.include_tasks:
        file: tasks/deploy-beszel.yaml
